production:
  adapter: redis
  url: redis://redistogo:a49c22eebce69799195de9ce3e1ed140@viperfish.redistogo.com:11736/

development:
  adapter: redis
  url: redis://localhost:6379/2

test:
  adapter: async
